# Default values for varnish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: varnish
  tag: 6.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Port where varnish expects requests on
service:
  port: 80

# Deploying Tomcat for Demo Purposes, otherwise
# Varnish won't start without an existing service to connect to
tomcat:
  enabled: true
  service:
    type: ClusterIP
  

# Use this property to provide a full varnish config
# consider disabling Tomcat above as well
# varnishConfigPath: varnish.vcl

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
