apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "varnish.fullname" . }}-config-map"
  labels:
{{ include "varnish.labels" . | indent 4 }}
data:
{{- if .Values.varnishConfigContent }}
  default.vcl: |
{{ .Values.varnishConfigContent | indent 4 }}
{{- else }}
  default.vcl: |
    vcl 4.0;

    backend default {
      .host = "{{ include "varnish.fullname" . }}-tomcat";
      .port = "8080";
    }

{{- end }}
