apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
{{ include "varnish.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "varnish.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
